### ISSUE TITLE
seeedstudio settings for printing

### ISSUE THREAD

**Issue by SidhNor** [fishpepper/pagoda-antenna#1]
Hi,
Would you be able to share/confirm seeedstudio settings for ordering these 4x4?

Setting | Value
------------ | -------------
Material | FR-4 TG130
Layers | 2
Dimensions | 100x100mm
PCB Qty | 10
Panelized PCBs | 1
PCB Thickness | 1mm
PCB Color | whatever
Surface Finish | HASL
Copper Weight | 1oz
Min Hole Size | 0.3mm
Min Tracking / Spacing | 6.6 mil
Blind Vias | no
Half-cut / Castellated Holes | no
Impedance Control | no

As far as I understand, you would have to order 3 pieces separately with the same settings. That will amount to a total of 16 x 10 plates of 3 types. So its about 160 antennas.

Thank you,
Gleb

**Comment by fishpepper** [comment]
Thats correct :)
